import SubscriptionPlan from "../models/SubscriptionPlan.js";

const starterFeatures = [
  "Dashboard",
  "Vehicle Management",
  "Customer Management",
  "Booking Management",
  "Payment History",
  "QR Code Generation",
  "Customer Verification",
  "Email Notifications",
  "Razorpay Integration",
  "Basic Revenue Analytics",
  "Company Logo",
  "Company Profile",
  "Company Information",
  "Invoice Generation",
  "Basic Reports",
  "Free SaaS Subdomain",
  "Subscription Management",
  "Profile Settings",
  "Basic Security",
];

const professionalFeatures = [
  ...starterFeatures,
  "Custom Domain",
  "Theme Customization",
  "Staff Management",
  "Role & Permission Management",
  "Branch Management",
  "Coupons",
  "Discount Campaigns",
  "Google Analytics",
  "SEO Settings",
  "WhatsApp Notifications",
  "SMS Notifications",
  "PayU Integration",
  "UPI Integration",
  "Multiple Payment Options",
  "Maintenance Management",
  "Vehicle Service Reminder",
  "Customer Reviews",
  "Advanced Reports",
  "Advanced Analytics Dashboard",
  "Revenue Graphs",
  "Business Insights",
  "Priority Support",
];

const enterpriseFeatures = [
  ...professionalFeatures,
  "Complete White Label Solution",
  "Multiple Custom Domains",
  "Advanced Theme Builder",
  "Custom Branding",
  "Custom Login Page",
  "Custom Dashboard Branding",
  "Custom Invoice Design",
  "Custom Email Templates",
  "Custom Notification Templates",
  "CRM Module",
  "API Access",
  "Advanced Business Analytics",
  "Fleet Analytics",
  "Customer Behaviour Analytics",
  "Marketing Dashboard",
  "Loyalty Program",
  "Referral Program",
  "Backup & Restore",
  "Export to PDF, Excel & CSV",
  "Dedicated Account Manager",
  "Feature Flag Management",
  "Multi-language Support",
  "Third-party Integrations",
  "Future Mobile App Branding Support",
];

const pricingFaqs = [
  {
    question: "Can I upgrade later?",
    answer: "Yes. When a client upgrades, newly included modules appear automatically from database entitlements.",
  },
  {
    question: "Can Starter use a custom domain?",
    answer: "No. Starter receives a free SaaS subdomain. Custom domains begin with Professional.",
  },
  {
    question: "Does Enterprise include unlimited usage?",
    answer: "Enterprise limits are stored as 0, which means unlimited under fair usage policy.",
  },
  {
    question: "Are hidden features secure?",
    answer: "Yes. The frontend hides them and backend route and gateway checks enforce plan access.",
  },
];

const comparisonFeatures = [
  ["Dashboard", "dashboard", "Core"],
  ["Vehicle Management", "vehicleManagement", "Core"],
  ["Customer Management", "customerManagement", "Core"],
  ["Booking Management", "bookingManagement", "Core"],
  ["Payment History", "paymentHistory", "Core"],
  ["Custom Domain", "customDomain", "Branding"],
  ["Theme Builder", "themeBuilder", "Branding"],
  ["White Label Branding", "whiteLabelBranding", "Branding"],
  ["Branch Management", "branchManagement", "Operations"],
  ["Staff Management", "staffManagement", "Operations"],
  ["Staff Roles & Permissions", "rolePermissions", "Operations"],
  ["Coupons", "coupons", "Growth"],
  ["Discount Campaigns", "discountCampaigns", "Growth"],
  ["Marketing Tools", "marketingTools", "Growth"],
  ["Google Analytics", "googleAnalytics", "Analytics"],
  ["Facebook Pixel", "facebookPixel", "Analytics"],
  ["SEO Settings", "seoSettings", "Growth"],
  ["WhatsApp Notifications", "whatsappNotifications", "Notifications"],
  ["SMS Notifications", "smsNotifications", "Notifications"],
  ["Multiple Payment Gateways", "multiplePaymentGateways", "Payments"],
  ["PayU Integration", "payuIntegration", "Payments"],
  ["UPI Integration", "upiIntegration", "Payments"],
  ["CRM", "crm", "Enterprise"],
  ["API Access", "apiAccess", "Enterprise"],
  ["Advanced Reports", "advancedReports", "Analytics"],
  ["Backup & Restore", "backupRestore", "Enterprise"],
  ["Multi-language Support", "multiLanguage", "Enterprise"],
].map(([label, featureKey, category], index) => ({ label, featureKey, category, sortOrder: index + 1 }));

const baseNavigationItems = [
  { label: "Overview", route: "/tenant", icon: "LayoutDashboard", featureKey: "dashboard", exact: true, sortOrder: 1 },
  { label: "Fleet", route: "/tenant/fleet", icon: "Bike", featureKey: "vehicleManagement", sortOrder: 2 },
  { label: "Customers", route: "/tenant/users", icon: "Users", featureKey: "customerManagement", sortOrder: 3 },
  { label: "Bookings", route: "/tenant/bookings", icon: "BookOpenCheck", featureKey: "bookingManagement", sortOrder: 4 },
  { label: "Orders", route: "/tenant/orders", icon: "ShoppingBag", featureKey: "bookingManagement", sortOrder: 5 },
  { label: "Payments", route: "/tenant/payments", icon: "CreditCard", featureKey: "paymentHistory", sortOrder: 6 },
  { label: "Settings", route: "/tenant/settings", icon: "Settings", featureKey: "profileSettings", sortOrder: 99 },
];

const professionalNavigationItems = [
  ...baseNavigationItems,
  { label: "Branches", route: "/tenant/settings?tab=branches", icon: "Building2", featureKey: "branchManagement", sortOrder: 7 },
  { label: "Staff", route: "/tenant/users?tab=staff", icon: "UserCog", featureKey: "staffManagement", sortOrder: 8 },
];

const enterpriseNavigationItems = [
  ...professionalNavigationItems,
  { label: "CRM", route: "/tenant/settings?tab=crm", icon: "Handshake", featureKey: "crm", sortOrder: 9 },
  { label: "API", route: "/tenant/settings?tab=api", icon: "KeyRound", featureKey: "apiAccess", sortOrder: 10 },
];

const billingCyclesFor = (monthlyPrice, yearlyPrice) => [
  { cycle: "monthly", label: "Monthly", price: monthlyPrice, months: 1, active: true, sortOrder: 1 },
  { cycle: "half_yearly", label: "Half-Yearly", price: monthlyPrice * 6, months: 6, active: true, sortOrder: 2 },
  { cycle: "yearly", label: "Yearly", price: yearlyPrice, months: 12, active: true, sortOrder: 3 },
];

const featureFlags = {
  starter: {
    dashboard: true,
    vehicleManagement: true,
    customerManagement: true,
    bookingManagement: true,
    paymentHistory: true,
    qrCodeGeneration: true,
    customerVerification: true,
    emailNotifications: true,
    razorpayIntegration: true,
    basicRevenueAnalytics: true,
    companyLogo: true,
    companyProfile: true,
    companyInformation: true,
    invoiceGeneration: true,
    basicReports: true,
    freeSubdomain: true,
    subscriptionManagement: true,
    profileSettings: true,
    basicSecurity: true,
    customDomain: false,
    themeBuilder: false,
    whiteLabelBranding: false,
    staffManagement: false,
    rolePermissions: false,
    branchManagement: false,
    coupons: false,
    discountCampaigns: false,
    marketingTools: false,
    whatsappNotifications: false,
    smsNotifications: false,
    payuIntegration: false,
    upiIntegration: false,
    multiplePaymentGateways: false,
    googleAnalytics: false,
    facebookPixel: false,
    seoSettings: false,
    apiAccess: false,
    crm: false,
    advancedReports: false,
    backupRestore: false,
  },
  professional: {
    dashboard: true,
    vehicleManagement: true,
    customerManagement: true,
    bookingManagement: true,
    paymentHistory: true,
    qrCodeGeneration: true,
    customerVerification: true,
    emailNotifications: true,
    razorpayIntegration: true,
    basicRevenueAnalytics: true,
    companyLogo: true,
    companyProfile: true,
    companyInformation: true,
    invoiceGeneration: true,
    basicReports: true,
    freeSubdomain: true,
    subscriptionManagement: true,
    profileSettings: true,
    basicSecurity: true,
    customDomain: true,
    themeBuilder: "basic",
    staffManagement: true,
    rolePermissions: true,
    branchManagement: true,
    coupons: true,
    discountCampaigns: true,
    marketingTools: true,
    googleAnalytics: true,
    facebookPixel: true,
    seoSettings: true,
    seoTools: true,
    whatsappNotifications: true,
    smsNotifications: true,
    payuIntegration: true,
    upiIntegration: true,
    multiplePaymentGateways: true,
    maintenanceManagement: true,
    maintenanceModule: true,
    serviceReminder: true,
    customerReviews: true,
    advancedReports: true,
    advancedAnalytics: true,
    revenueGraphs: true,
    businessInsights: true,
    prioritySupport: true,
    whiteLabelBranding: false,
    apiAccess: false,
    crm: false,
    backupRestore: false,
    enterpriseAnalytics: false,
  },
  enterprise: {
    dashboard: true,
    vehicleManagement: true,
    customerManagement: true,
    bookingManagement: true,
    paymentHistory: true,
    qrCodeGeneration: true,
    customerVerification: true,
    emailNotifications: true,
    razorpayIntegration: true,
    basicRevenueAnalytics: true,
    companyLogo: true,
    companyProfile: true,
    companyInformation: true,
    invoiceGeneration: true,
    basicReports: true,
    freeSubdomain: true,
    subscriptionManagement: true,
    profileSettings: true,
    basicSecurity: true,
    customDomain: true,
    themeBuilder: "advanced",
    staffManagement: true,
    rolePermissions: true,
    branchManagement: true,
    coupons: true,
    discountCampaigns: true,
    marketingTools: true,
    googleAnalytics: true,
    facebookPixel: true,
    seoSettings: true,
    seoTools: true,
    whatsappNotifications: true,
    smsNotifications: true,
    payuIntegration: true,
    upiIntegration: true,
    stripeIntegration: true,
    multiplePaymentGateways: true,
    maintenanceManagement: true,
    maintenanceModule: true,
    serviceReminder: true,
    customerReviews: true,
    advancedReports: true,
    advancedAnalytics: true,
    revenueGraphs: true,
    businessInsights: true,
    prioritySupport: true,
    completeWhiteLabel: true,
    whiteLabelBranding: true,
    customLoginPage: true,
    customDashboardBranding: true,
    customInvoiceBranding: true,
    customEmailTemplates: true,
    customNotificationTemplates: true,
    crm: true,
    apiAccess: true,
    enterpriseAnalytics: true,
    fleetAnalytics: true,
    customerBehaviourAnalytics: true,
    marketingDashboard: true,
    loyaltyProgram: true,
    referralProgram: true,
    backupRestore: true,
    exports: true,
    dedicatedAccountManager: true,
    featureFlagManagement: true,
    multiLanguage: true,
    thirdPartyIntegrations: true,
    mobileAppBranding: true,
  },
};

const defaultPlans = [
  {
    name: "Starter",
    code: "starter",
    monthlyPrice: 799,
    yearlyPrice: 7990,
    billingCycles: billingCyclesFor(799, 7990),
    bikeLimit: 25,
    staffLimit: 2,
    branchLimit: 1,
    bookingLimit: 500,
    storageLimitMb: 1024,
    bandwidthLimitGb: 25,
    apiLimitMonthly: 0,
    customDomainLimit: 0,
    analyticsLevel: "basic",
    supportLevel: "standard",
    customBranding: false,
    apiAccess: false,
    digitalAgreements: false,
    whatsappIntegration: false,
    advancedReports: false,
    inventory: false,
    crm: false,
    maintenanceModule: false,
    featureFlags: featureFlags.starter,
    gatewayAvailability: { razorpay: true, payu: false, stripe: false, upi: false, cash: true, bankTransfer: false },
    recommendedFor: "Small Bike & Scooter Rental Businesses",
    featureList: starterFeatures,
    hiddenFeatureList: [
      "Custom Domain",
      "Theme Builder",
      "White Label Branding",
      "Staff Roles & Permissions",
      "Branch Management",
      "Coupons",
      "Marketing Tools",
      "WhatsApp Notifications",
      "SMS Notifications",
      "PayU Integration",
      "UPI Integration",
      "Multiple Payment Gateways",
      "Google Analytics",
      "Facebook Pixel",
      "SEO Settings",
      "API Access",
      "CRM",
      "Advanced Reports",
      "Backup & Restore",
    ],
    navigationItems: baseNavigationItems,
    comparisonFeatures,
    faqs: pricingFaqs,
    planBadges: [],
    sortOrder: 1,
    active: true,
  },
  {
    name: "Professional",
    code: "professional",
    monthlyPrice: 999,
    yearlyPrice: 9990,
    billingCycles: billingCyclesFor(999, 9990),
    bikeLimit: 100,
    staffLimit: 10,
    branchLimit: 3,
    bookingLimit: 5000,
    storageLimitMb: 10240,
    bandwidthLimitGb: 250,
    apiLimitMonthly: 0,
    customDomainLimit: 1,
    analyticsLevel: "advanced",
    supportLevel: "priority",
    customBranding: false,
    apiAccess: false,
    digitalAgreements: true,
    whatsappIntegration: true,
    advancedReports: true,
    inventory: true,
    crm: false,
    maintenanceModule: true,
    featureFlags: featureFlags.professional,
    gatewayAvailability: { razorpay: true, payu: true, stripe: false, upi: true, cash: true, bankTransfer: true },
    recommendedFor: "Growing Rental Businesses",
    featureList: professionalFeatures,
    hiddenFeatureList: [
      "White Label Mobile App",
      "API Access",
      "CRM",
      "Multiple Custom Domains",
      "White Label Branding",
      "Custom Email Templates",
      "Custom Invoice Branding",
      "Backup & Restore",
      "Enterprise Analytics",
    ],
    navigationItems: professionalNavigationItems,
    comparisonFeatures,
    faqs: pricingFaqs,
    planBadges: ["Most Popular"],
    sortOrder: 2,
    active: true,
  },
  {
    name: "Enterprise",
    code: "enterprise",
    monthlyPrice: 1199,
    yearlyPrice: 11990,
    billingCycles: billingCyclesFor(1199, 11990),
    bikeLimit: 0,
    staffLimit: 0,
    branchLimit: 0,
    bookingLimit: 0,
    storageLimitMb: 0,
    bandwidthLimitGb: 0,
    apiLimitMonthly: 0,
    customDomainLimit: 0,
    analyticsLevel: "full",
    supportLevel: "dedicated",
    customBranding: true,
    apiAccess: true,
    digitalAgreements: true,
    whatsappIntegration: true,
    advancedReports: true,
    inventory: true,
    crm: true,
    maintenanceModule: true,
    featureFlags: featureFlags.enterprise,
    gatewayAvailability: { razorpay: true, payu: true, stripe: true, upi: true, cash: true, bankTransfer: true },
    recommendedFor: "Large Rental Companies & Franchise Businesses",
    featureList: enterpriseFeatures,
    hiddenFeatureList: [],
    navigationItems: enterpriseNavigationItems,
    comparisonFeatures,
    faqs: pricingFaqs,
    planBadges: ["Best Value"],
    sortOrder: 3,
    active: true,
  },
];

const seedSubscriptionPlans = async () => {
  await Promise.all(
    defaultPlans.map((plan) =>
      SubscriptionPlan.updateOne(
        { code: plan.code },
        { $set: plan },
        { upsert: true }
      )
    )
  );
};

export default seedSubscriptionPlans;
