import mongoose from "mongoose";

const tenantSettingsSchema = new mongoose.Schema(
  {
    tenantId: { type: mongoose.Schema.Types.ObjectId, ref: "Tenant", required: true, unique: true, index: true },
    paymentMethods: {
      razorpay: {
        enabled: { type: Boolean, default: false },
        keyId: { type: String, trim: true },
        keySecret: { type: String, trim: true },
        webhookSecret: { type: String, trim: true },
      },
      payu: {
        enabled: { type: Boolean, default: false },
        merchantKey: { type: String, trim: true },
        salt: { type: String, trim: true },
      },
      stripe: {
        enabled: { type: Boolean, default: false },
        publishableKey: { type: String, trim: true },
        secretKey: { type: String, trim: true },
        webhookSecret: { type: String, trim: true },
      },
      upi: {
        enabled: { type: Boolean, default: false },
        upiId: { type: String, trim: true },
        displayName: { type: String, trim: true },
        webhookSecret: { type: String, trim: true },
      },
      cash: {
        enabled: { type: Boolean, default: true },
      },
      bankTransfer: {
        enabled: { type: Boolean, default: false },
        accountName: { type: String, trim: true },
        accountNumber: { type: String, trim: true },
        ifsc: { type: String, trim: true },
        bankName: { type: String, trim: true },
      },
    },
    branding: {
      logoUrl: { type: String, trim: true },
      dashboardLogoUrl: { type: String, trim: true },
      faviconUrl: { type: String, trim: true },
      watermarkUrl: { type: String, trim: true },
      homepageBannerUrl: { type: String, trim: true },
      loginBackgroundUrl: { type: String, trim: true },
      companyDisplayName: { type: String, trim: true },
      supportEmail: { type: String, trim: true },
      supportPhone: { type: String, trim: true },
      address: { type: String, trim: true },
      footerText: { type: String, trim: true },
      socialLinks: {
        facebook: { type: String, trim: true },
        instagram: { type: String, trim: true },
        x: { type: String, trim: true },
        linkedin: { type: String, trim: true },
        youtube: { type: String, trim: true },
        whatsapp: { type: String, trim: true },
      },
    },
    theme: {
      mode: { type: String, enum: ["light", "dark", "auto"], default: "light" },
      primaryColor: { type: String, default: "#0b5ed7", trim: true },
      secondaryColor: { type: String, default: "#f4f7fb", trim: true },
      accentColor: { type: String, default: "#ef4444", trim: true },
      buttonStyle: { type: String, enum: ["rounded", "pill", "square"], default: "rounded" },
      borderRadius: { type: Number, default: 12, min: 0, max: 32 },
      typography: { type: String, default: "Plus Jakarta Sans", trim: true },
      sidebarStyle: { type: String, enum: ["compact", "comfortable", "floating"], default: "comfortable" },
      headerStyle: { type: String, enum: ["classic", "centered", "minimal"], default: "classic" },
      footerStyle: { type: String, enum: ["simple", "expanded", "hidden"], default: "simple" },
      homepageLayout: { type: String, enum: ["marketplace", "brand", "compact"], default: "marketplace" },
      cardDesign: { type: String, enum: ["classic", "premium", "minimal"], default: "premium" },
      animations: { type: Boolean, default: true },
      logoPlacement: { type: String, enum: ["left", "center"], default: "left" },
      customCss: { type: String },
    },
    domain: {
      activeMode: { type: String, enum: ["subdomain", "custom"], default: "subdomain" },
      freeSubdomain: { type: String, lowercase: true, trim: true },
      primaryDomain: { type: String, lowercase: true, trim: true },
      customDomains: [{
        domain: { type: String, lowercase: true, trim: true },
        status: { type: String, enum: ["pending_verification", "verified", "expired", "disconnected"], default: "pending_verification" },
        verificationToken: { type: String, trim: true },
        sslStatus: { type: String, enum: ["pending", "active", "failed", "expired"], default: "pending" },
        verifiedAt: { type: Date },
      }],
    },
    invoice: {
      gstNumber: { type: String, trim: true },
      taxPercent: { type: Number, default: 0, min: 0 },
      prefix: { type: String, default: "INV", trim: true },
      design: { type: String, enum: ["classic", "modern", "minimal"], default: "modern" },
      headerHtml: { type: String },
      footerHtml: { type: String },
    },
    businessHours: {
      open: { type: String, default: "09:00" },
      close: { type: String, default: "21:00" },
    },
    policies: {
      privacyPolicy: { type: String },
      termsAndConditions: { type: String },
      refundPolicy: { type: String },
      cancellationPolicy: { type: String },
      bookingRules: { type: String },
      vehicleRules: { type: String },
    },
    seo: {
      metaTitle: { type: String, trim: true },
      metaDescription: { type: String, trim: true },
      keywords: [{ type: String, trim: true }],
      canonicalUrl: { type: String, trim: true },
      openGraphImage: { type: String, trim: true },
      twitterCard: { type: String, trim: true },
      schemaMarkup: { type: String },
      robotsTxt: { type: String },
      googleAnalyticsId: { type: String, trim: true },
      googleSearchConsoleVerification: { type: String, trim: true },
      metaPixelId: { type: String, trim: true },
      googleTagManagerId: { type: String, trim: true },
      customHeadScripts: { type: String },
    },
    templates: {
      email: { bookingConfirmation: { type: String }, paymentReceipt: { type: String }, cancellation: { type: String } },
      sms: { bookingConfirmation: { type: String }, paymentReceipt: { type: String }, cancellation: { type: String } },
      whatsapp: { bookingConfirmation: { type: String }, paymentReceipt: { type: String }, cancellation: { type: String } },
    },
    localization: {
      defaultLanguage: { type: String, default: "en", trim: true },
      enabledLanguages: [{ type: String, trim: true }],
    },
    integrations: {
      googleAnalytics: { enabled: { type: Boolean, default: false } },
      metaPixel: { enabled: { type: Boolean, default: false } },
      googleTagManager: { enabled: { type: Boolean, default: false } },
      whatsapp: { enabled: { type: Boolean, default: false }, provider: { type: String, trim: true }, apiKey: { type: String, trim: true } },
      sms: { enabled: { type: Boolean, default: false }, provider: { type: String, trim: true }, apiKey: { type: String, trim: true } },
    },
    mobileBranding: {
      appLogoUrl: { type: String, trim: true },
      splashScreenUrl: { type: String, trim: true },
      appIconUrl: { type: String, trim: true },
      packageName: { type: String, trim: true },
      firebaseConfigJson: { type: String },
    },
    hostingUsage: {
      storageUsedMb: { type: Number, default: 0, min: 0 },
      bandwidthUsedGb: { type: Number, default: 0, min: 0 },
      imagesStored: { type: Number, default: 0, min: 0 },
      documentsStored: { type: Number, default: 0, min: 0 },
      apiUsageMonthly: { type: Number, default: 0, min: 0 },
      databaseUsageMb: { type: Number, default: 0, min: 0 },
      monthlyTraffic: { type: Number, default: 0, min: 0 },
      status: { type: String, enum: ["healthy", "warning", "limited"], default: "healthy" },
    },
  },
  { timestamps: true }
);

export default mongoose.model("TenantSettings", tenantSettingsSchema);
